 var planets=[
    {
      "name": "Mercury",
      "diameter (Earth=1)": 0.382,
      "diameter (km)": 4878,
      "mass (Earth=1)": 0.055,
      "mean distance from Sun (AU)": 0.39,
      "orbital period (Earth years)": 0.24,
      "orbital eccentricity": 0.2056,
      "mean orbital velocity (km/sec)": 47.89,
      "rotation period (in Earth days)": 58.65,
      "inclination of axis (degrees)": 0.0,
      "mean temperature at surface (C)": {"from": -180, "to": 430},
      "gravity at equator (Earth=1)": 0.38,
      "escape velocity (km/sec)": 4.25,
      "mean density (water=1)": 5.43,
      "atmospheric composition": "none",
      "number of moons": 0,
      "rings?": false
    },
    {
      "name": "Venus",
      "diameter (Earth=1)": 0.949,
      "diameter (km)": 12104,
      "mass (Earth=1)": 0.815,
      "mean distance from Sun (AU)": 0.72,
      "orbital period (Earth years)": 0.62,
      "orbital eccentricity": 0.0068,
      "mean orbital velocity (km/sec)": 35.03,
      "rotation period (in Earth days)": "-243*",
      "inclination of axis (degrees)": 177.4,
      "mean temperature at surface (C)": {"from": 465, "to": 465},
      "gravity at equator (Earth=1)": 0.9,
      "escape velocity (km/sec)": 10.36,
      "mean density (water=1)": 5.25,
      "atmospheric composition": "CO2",
      "number of moons": 0,
      "rings?": false
    },
    {
      "name": "Earth",
      "diameter (Earth=1)": 1,
      "diameter (km)": 12756,
      "mass (Earth=1)": 1,
      "mean distance from Sun (AU)": 1,
      "orbital period (Earth years)": 1,
      "orbital eccentricity": 0.0167,
      "mean orbital velocity (km/sec)": 29.79,
      "rotation period (in Earth days)": 1,
      "inclination of axis (degrees)": 23.45,
      "mean temperature at surface (C)": {"from": -89, "to": 58},
      "gravity at equator (Earth=1)": 1,
      "escape velocity (km/sec)": 11.18,
      "mean density (water=1)": 5.52,
      "atmospheric composition": "N2 + O2",
      "number of moons": 1,
      "rings?": false
    },
    {
      "name": "Mars",
      "diameter (Earth=1)": 0.532,
      "diameter (km)": 6787,
      "mass (Earth=1)": 0.107,
      "mean distance from Sun (AU)": 1.52,
      "orbital period (Earth years)": 1.88,
      "orbital eccentricity": 0.0934,
      "mean orbital velocity (km/sec)": 24.13,
      "rotation period (in Earth days)": 1.03,
      "inclination of axis (degrees)": 23.98,
      "mean temperature at surface (C)": {"from": -82, "to": 0},
      "gravity at equator (Earth=1)": 0.38,
      "escape velocity (km/sec)": 5.02,
      "mean density (water=1)": 3.93,
      "atmospheric composition": "CO2",
      "number of moons": 2,
      "rings?": false
    },
    {
      "name": "Jupiter",
      "diameter (Earth=1)": 11.209,
      "diameter (km)": 142800,
      "mass (Earth=1)": 318,
      "mean distance from Sun (AU)": 5.20,
      "orbital period (Earth years)": 11.86,
      "orbital eccentricity": 0.0483,
      "mean orbital velocity (km/sec)": 13.06,
      "rotation period (in Earth days)": 0.41,
      "inclination of axis (degrees)": 3.08,
      "mean temperature at surface (C)": {"from": -150, "to": -150},
      "gravity at equator (Earth=1)": 2.64,
      "escape velocity (km/sec)": 59.54,
      "mean density (water=1)": 1.33,
      "atmospheric composition": "H2+He",
      "number of moons": 67,
      "rings?": true
    },
    {
      "name": "Saturn",
      "diameter (Earth=1)": 9.44,
      "diameter (km)": 120000,
      "mass (Earth=1)": 95,
      "mean distance from Sun (AU)": 9.54,
      "orbital period (Earth years)": 29.46,
      "orbital eccentricity": 0.0560,
      "mean orbital velocity (km/sec)": 9.64,
      "rotation period (in Earth days)": 0.44,
      "inclination of axis (degrees)": 26.73,
      "mean temperature at surface (C)": {"from": -170, "to": -170},
      "gravity at equator (Earth=1)": 0.93,
      "escape velocity (km/sec)": 35.49,
      "mean density (water=1)": 0.71,
      "atmospheric composition": "H2+He",
      "number of moons": 62,
      "rings?": true
    },
    {
      "name": "Uranus",
      "diameter (Earth=1)": 4.007,
      "diameter (km)": 51118,
      "mass (Earth=1)": 15,
      "mean distance from Sun (AU)": 19.18,
      "orbital period (Earth years)": 84.01,
      "orbital eccentricity": 0.0461,
      "mean orbital velocity (km/sec)": 6.81,
      "rotation period (in Earth days)": -0.72,
      "inclination of axis (degrees)": 97.92,
      "mean temperature at surface (C)": {"from": -200, "to": -200},
      "gravity at equator (Earth=1)": 0.89,
      "escape velocity (km/sec)": 21.29,
      "mean density (water=1)": 1.24,
      "atmospheric composition": "H2+He",
      "number of moons": 27,
      "rings?": true
    },
    {
      "name": "Neptune",
      "diameter (Earth=1)": 3.883,
      "diameter (km)": 49528,
      "mass (Earth=1)": 17,
      "mean distance from Sun (AU)": 30.06,
      "orbital period (Earth years)": 164.8,
      "orbital eccentricity": 0.0097,
      "mean orbital velocity (km/sec)": 5.43,
      "rotation period (in Earth days)": 0.72,
      "inclination of axis (degrees)": 28.8,
      "mean temperature at surface (C)": {"from": -210, "to": -210},
      "gravity at equator (Earth=1)": 1.12,
      "escape velocity (km/sec)": 23.71,
      "mean density (water=1)": 1.67,
      "atmospheric composition": "H2+He",
      "number of moons": 14,
      "rings?": true
    }
  ]
